CREATE TABLE CAT_PROSPECTOS(
PROSPECTO_ID INT PRIMARY KEY,
NOMBRE VARCHAR(100),
APELLIDO_PATERNO VARCHAR(100),
APELLIDO_MATERNO VARCHAR(100),
CALLE varchar(250),
NUMERO VARCHAR(100),
COLONIA VARCHAR(100),
CODIGO_POSTAL VARCHAR(10),
TELEFONO VARCHAR(20),
RFC VARCHAR(20),
ESTATUS INT,
OBSERVACIONES VARCHAR(MAX),
ULTIMAACT TIMESTAMP
)