CREATE TABLE CAT_PROSPECTOS_ADJUNTOS(
PROSPECTOADJUNTO_ID INT PRIMARY KEY,
PROSPECTO_ID INT,
TIPODOCUMENTO_ID INT,
TIPODOCUMENTO VARCHAR(250), --Acta de Nacimiento
PATH_FILE VARCHAR(100), --Nombre del archivo o ruta 
ESTATUS INT,
FECHA_CREACION DATETIME,
FILE_UPLOAD IMAGE,
ULTIMAACT TIMESTAMP
)